on:
  pull_request:
  push: 
    paths:
      - .github/workflows/compile-css.yaml
      - source/**
      - source/**/**
      - postinstall.sh
      - squash-a-script.sh
      - squash-sass.sh
      - package.json
      - package-lock.json

name: Render CSS and Javascript

jobs:
  compress-everything:
    name: Render css/javascript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clean
        run: rm -rf inst/pkgdown/assets/assets/
      - uses: actions/setup-node@v4
      - run: npm install
      - name: Comple js
        run: bash squash-a-script.sh
      - name: Compile sass
        run: bash squash-sass.sh
      - name: Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add assets/ || echo ""
          git add inst/ || echo ""
          git commit -m 'regenerated css/js' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

